"""initial core schema

Revision ID: 0001_core_schema
Revises:
Create Date: 2026-08-28 12:26:37.286745
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_core_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_jobs",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column("schema_version", sa.String(length=16), server_default="1.0", nullable=False),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("response_payload", sa.JSON(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','CANCELLED')",
            name=op.f("ck_ai_jobs_status"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_ai_jobs_attempts_nonnegative")),
        sa.CheckConstraint(
            "max_attempts BETWEEN 1 AND 100", name=op.f("ck_ai_jobs_max_attempts_range")
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_ai_jobs")),
        sa.UniqueConstraint("idempotency_key", name="uq_ai_jobs_idempotency_key"),
    )
    op.create_index(
        "ix_ai_jobs_provider_created", "ai_jobs", ["provider", "created_at"], unique=False
    )
    op.create_index(
        "ix_ai_jobs_status_available", "ai_jobs", ["status", "available_at"], unique=False
    )
    op.create_table(
        "devices",
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("device_type", sa.String(length=16), server_default="OTHER", nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="UNKNOWN", nullable=False),
        sa.Column("agent_version", sa.String(length=32), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_state_version", sa.Integer(), nullable=True),
        sa.Column(
            "core_reachable", sa.Boolean(), server_default=sa.text("(false)"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "device_type IN ('WINDOWS','WEB','MOBILE','SERVER','OTHER')",
            name=op.f("ck_devices_device_type"),
        ),
        sa.CheckConstraint(
            "status IN ('ONLINE','OFFLINE','DEGRADED','UNKNOWN')", name=op.f("ck_devices_status")
        ),
        sa.PrimaryKeyConstraint("device_id", name=op.f("pk_devices")),
    )
    op.create_index(
        "ix_devices_status_heartbeat", "devices", ["status", "last_heartbeat_at"], unique=False
    )
    op.create_table(
        "event_ledger",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.String(length=16), server_default="1.0", nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.Column("causation_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_event_ledger")),
        sa.UniqueConstraint("idempotency_key", name="uq_event_ledger_idempotency_key"),
    )
    op.create_index("ix_event_ledger_correlation", "event_ledger", ["correlation_id"], unique=False)
    op.create_index(
        "ix_event_ledger_entity_received",
        "event_ledger",
        ["entity_type", "entity_id", "received_at"],
        unique=False,
    )
    op.create_index(
        "ix_event_ledger_type_occurred", "event_ledger", ["event_type", "occurred_at"], unique=False
    )
    op.create_table(
        "fixed_events",
        sa.Column("fixed_event_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "display_timezone", sa.String(length=64), server_default="Asia/Shanghai", nullable=False
        ),
        sa.Column("location", sa.String(length=128), nullable=True),
        sa.Column("hardness", sa.String(length=16), server_default="HARD", nullable=False),
        sa.Column("activity_profile", sa.String(length=32), server_default="CLASS", nullable=False),
        sa.Column(
            "travel_before_minutes", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "travel_after_minutes", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("recurrence_rule", sa.String(length=500), nullable=True),
        sa.Column("external_source", sa.String(length=64), nullable=True),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "activity_profile IN "
            "('READING','WRITING','CODING','CLASS','ADMIN',"
            "'PHYSICAL','PASSIVE_VIDEO','OTHER')",
            name=op.f("ck_fixed_events_activity_profile"),
        ),
        sa.CheckConstraint(
            "hardness IN ('HARD','REQUIRED','SOFT')", name=op.f("ck_fixed_events_hardness")
        ),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_fixed_events_valid_interval")),
        sa.CheckConstraint(
            "travel_after_minutes BETWEEN 0 AND 1440",
            name=op.f("ck_fixed_events_travel_after_range"),
        ),
        sa.CheckConstraint(
            "travel_before_minutes BETWEEN 0 AND 1440",
            name=op.f("ck_fixed_events_travel_before_range"),
        ),
        sa.PrimaryKeyConstraint("fixed_event_id", name=op.f("pk_fixed_events")),
        sa.UniqueConstraint(
            "external_source", "external_id", name="uq_fixed_events_external_source_id"
        ),
    )
    op.create_index(
        "ix_fixed_events_start_end", "fixed_events", ["start_at", "end_at"], unique=False
    )
    op.create_table(
        "plan_versions",
        sa.Column("plan_version_id", sa.Uuid(), nullable=False),
        sa.Column("plan_date", sa.Date(), nullable=False),
        sa.Column(
            "display_timezone", sa.String(length=64), server_default="Asia/Shanghai", nullable=False
        ),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("based_on_plan_version_id", sa.Uuid(), nullable=True),
        sa.Column("trigger", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_state_version", sa.Integer(), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("conflicts", sa.JSON(), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "status IN ('FEASIBLE','PARTIAL','INFEASIBLE')", name=op.f("ck_plan_versions_status")
        ),
        sa.CheckConstraint(
            "trigger IN ('DAY_STARTED','USER_REQUESTED_REPLAN','TASK_COMPLETED_EARLY',"
            "'TASK_OVERRUN','BLOCK_MISSED','FIXED_EVENT_CHANGED','USER_REPORTED_FATIGUE',"
            "'USER_REPORTED_EMERGENCY','SESSION_ABORTED','AVAILABLE_TIME_CHANGED')",
            name=op.f("ck_plan_versions_trigger"),
        ),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_plan_versions_revision_positive")),
        sa.ForeignKeyConstraint(
            ["based_on_plan_version_id"],
            ["plan_versions.plan_version_id"],
            name=op.f("fk_plan_versions_based_on_plan_version_id_plan_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("plan_version_id", name=op.f("pk_plan_versions")),
        sa.UniqueConstraint(
            "plan_date",
            "display_timezone",
            "revision",
            name="uq_plan_versions_date_timezone_revision",
        ),
    )
    op.create_index(
        "ix_plan_versions_date_created", "plan_versions", ["plan_date", "created_at"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="BACKLOG", nullable=False),
        sa.Column("priority", sa.SmallInteger(), server_default=sa.text("3"), nullable=False),
        sa.Column("mandatory", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("remaining_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "minimum_chunk_minutes", sa.Integer(), server_default=sa.text("(25)"), nullable=False
        ),
        sa.Column("activity_profile", sa.String(length=32), server_default="OTHER", nullable=False),
        sa.Column("required_location", sa.String(length=128), nullable=True),
        sa.Column("required_device_capabilities", sa.JSON(), nullable=False),
        sa.Column("allowed_apps", sa.JSON(), nullable=False),
        sa.Column("blocked_apps", sa.JSON(), nullable=False),
        sa.Column(
            "idle_tolerance_seconds", sa.Integer(), server_default=sa.text("(300)"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "activity_profile IN "
            "('READING','WRITING','CODING','CLASS','ADMIN',"
            "'PHYSICAL','PASSIVE_VIDEO','OTHER')",
            name=op.f("ck_tasks_activity_profile"),
        ),
        sa.CheckConstraint(
            "status IN ('BACKLOG','READY','IN_PROGRESS','COMPLETED','CANCELLED')",
            name=op.f("ck_tasks_status"),
        ),
        sa.CheckConstraint(
            "estimated_minutes BETWEEN 1 AND 10080", name=op.f("ck_tasks_estimated_minutes_range")
        ),
        sa.CheckConstraint(
            "idle_tolerance_seconds BETWEEN 30 AND 7200", name=op.f("ck_tasks_idle_tolerance_range")
        ),
        sa.CheckConstraint(
            "minimum_chunk_minutes BETWEEN 5 AND 180", name=op.f("ck_tasks_minimum_chunk_range")
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name=op.f("ck_tasks_priority_range")),
        sa.CheckConstraint(
            "remaining_minutes BETWEEN 0 AND 10080", name=op.f("ck_tasks_remaining_minutes_range")
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_tasks")),
    )
    op.create_index("ix_tasks_mandatory_priority", "tasks", ["mandatory", "priority"], unique=False)
    op.create_index("ix_tasks_status_deadline", "tasks", ["status", "deadline"], unique=False)
    op.create_table(
        "daily_summaries",
        sa.Column("summary_id", sa.Uuid(), nullable=False),
        sa.Column("summary_date", sa.Date(), nullable=False),
        sa.Column(
            "display_timezone", sa.String(length=64), server_default="Asia/Shanghai", nullable=False
        ),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=True),
        sa.Column("source_plan_version_id", sa.Uuid(), nullable=True),
        sa.Column("source_plan_revision", sa.Integer(), nullable=True),
        sa.Column(
            "generated_by", sa.String(length=32), server_default="DETERMINISTIC", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "source_plan_revision IS NULL OR source_plan_revision >= 1",
            name=op.f("ck_daily_summaries_source_revision_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["source_plan_version_id"],
            ["plan_versions.plan_version_id"],
            name=op.f("fk_daily_summaries_source_plan_version_id_plan_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("summary_id", name=op.f("pk_daily_summaries")),
        sa.UniqueConstraint(
            "summary_date", "display_timezone", name="uq_daily_summaries_date_timezone"
        ),
    )
    op.create_index("ix_daily_summaries_date", "daily_summaries", ["summary_date"], unique=False)
    op.create_table(
        "device_role_leases",
        sa.Column("lease_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_for_state_version", sa.Integer(), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "role IN ('PRIMARY_INTERACTION','PRIMARY_ENFORCEMENT','SENSOR',"
            "'NOTIFICATION_ONLY','AI_WORKER','STANDBY')",
            name=op.f("ck_device_role_leases_role"),
        ),
        sa.CheckConstraint(
            "expires_at > issued_at", name=op.f("ck_device_role_leases_valid_interval")
        ),
        sa.CheckConstraint(
            "issued_for_state_version >= 1",
            name=op.f("ck_device_role_leases_state_version_positive"),
        ),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoked_at >= issued_at",
            name=op.f("ck_device_role_leases_revocation_after_issue"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
            name=op.f("fk_device_role_leases_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("lease_id", name=op.f("pk_device_role_leases")),
    )
    op.create_index(
        "ix_device_role_leases_device_expiry",
        "device_role_leases",
        ["device_id", "expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_device_role_leases_role_expiry",
        "device_role_leases",
        ["role", "expires_at"],
        unique=False,
    )
    op.create_table(
        "outbox",
        sa.Column("outbox_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING','PUBLISHED','FAILED')", name=op.f("ck_outbox_status")
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_outbox_attempts_nonnegative")),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event_ledger.event_id"],
            name=op.f("fk_outbox_event_id_event_ledger"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("outbox_id", name=op.f("pk_outbox")),
        sa.UniqueConstraint("event_id", name="uq_outbox_event_id"),
    )
    op.create_index("ix_outbox_locked", "outbox", ["locked_at"], unique=False)
    op.create_index(
        "ix_outbox_status_available", "outbox", ["status", "available_at"], unique=False
    )
    op.create_table(
        "plan_heads",
        sa.Column("plan_head_id", sa.Uuid(), nullable=False),
        sa.Column("plan_date", sa.Date(), nullable=False),
        sa.Column(
            "display_timezone", sa.String(length=64), server_default="Asia/Shanghai", nullable=False
        ),
        sa.Column("current_plan_version_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_plan_heads_revision_positive")),
        sa.ForeignKeyConstraint(
            ["current_plan_version_id"],
            ["plan_versions.plan_version_id"],
            name=op.f("fk_plan_heads_current_plan_version_id_plan_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("plan_head_id", name=op.f("pk_plan_heads")),
        sa.UniqueConstraint("plan_date", "display_timezone", name="uq_plan_heads_date_timezone"),
    )
    op.create_table(
        "schedule_blocks",
        sa.Column("block_id", sa.Uuid(), nullable=False),
        sa.Column("plan_version_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("fixed_event_id", sa.Uuid(), nullable=True),
        sa.Column("source_block_id", sa.Uuid(), nullable=True),
        sa.Column("hardness", sa.String(length=16), nullable=False),
        sa.Column("activity_profile", sa.String(length=32), nullable=False),
        sa.Column("allowed_apps", sa.JSON(), nullable=False),
        sa.Column("blocked_apps", sa.JSON(), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "activity_profile IN "
            "('READING','WRITING','CODING','CLASS','ADMIN',"
            "'PHYSICAL','PASSIVE_VIDEO','OTHER')",
            name=op.f("ck_schedule_blocks_activity_profile"),
        ),
        sa.CheckConstraint(
            "hardness IN ('HARD','REQUIRED','SOFT')", name=op.f("ck_schedule_blocks_hardness")
        ),
        sa.CheckConstraint(
            "kind IN ('FIXED_EVENT','TASK','TRAVEL','MEAL','SLEEP','BREAK','BUFFER','UNPLANNED')",
            name=op.f("ck_schedule_blocks_kind"),
        ),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_schedule_blocks_valid_interval")),
        sa.ForeignKeyConstraint(
            ["fixed_event_id"],
            ["fixed_events.fixed_event_id"],
            name=op.f("fk_schedule_blocks_fixed_event_id_fixed_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_version_id"],
            ["plan_versions.plan_version_id"],
            name=op.f("fk_schedule_blocks_plan_version_id_plan_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_block_id"],
            ["schedule_blocks.block_id"],
            name=op.f("fk_schedule_blocks_source_block_id_schedule_blocks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
            name=op.f("fk_schedule_blocks_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("block_id", name=op.f("pk_schedule_blocks")),
        sa.UniqueConstraint("plan_version_id", "block_id", name="uq_schedule_blocks_plan_block"),
    )
    op.create_index(
        "ix_schedule_blocks_plan_start",
        "schedule_blocks",
        ["plan_version_id", "start_at"],
        unique=False,
    )
    op.create_index(
        "ix_schedule_blocks_task_start", "schedule_blocks", ["task_id", "start_at"], unique=False
    )
    op.create_table(
        "execution_sessions",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("plan_version_id", sa.Uuid(), nullable=False),
        sa.Column("block_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("commitment_mode", sa.String(length=16), nullable=False),
        sa.Column("session_state", sa.String(length=24), server_default="PLANNED", nullable=False),
        sa.Column("scheduled_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dry_run", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column(
            "intervention_level", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("preauthorization", sa.JSON(), nullable=False),
        sa.Column("emergency_released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("override_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("override_reason", sa.String(length=500), nullable=True),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "commitment_mode IN ('ADVISORY','STANDARD','STRICT')",
            name=op.f("ck_execution_sessions_commitment_mode"),
        ),
        sa.CheckConstraint(
            "session_state IN ('PLANNED','DUE','STARTING','RUNNING','PAUSED',"
            "'INTERRUPTED','RECOVERY','COMPLETED','ABORTED','MISSED')",
            name=op.f("ck_execution_sessions_session_state"),
        ),
        sa.CheckConstraint(
            "actual_end_at IS NULL OR actual_start_at IS NULL OR actual_end_at >= actual_start_at",
            name=op.f("ck_execution_sessions_actual_interval"),
        ),
        sa.CheckConstraint(
            "intervention_level BETWEEN 0 AND 5",
            name=op.f("ck_execution_sessions_intervention_level_range"),
        ),
        sa.CheckConstraint(
            "scheduled_end_at > scheduled_start_at",
            name=op.f("ck_execution_sessions_scheduled_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["schedule_blocks.block_id"],
            name=op.f("fk_execution_sessions_block_id_schedule_blocks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
            name=op.f("fk_execution_sessions_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_version_id"],
            ["plan_versions.plan_version_id"],
            name=op.f("fk_execution_sessions_plan_version_id_plan_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
            name=op.f("fk_execution_sessions_task_id_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_execution_sessions")),
    )
    op.create_index(
        "ix_execution_sessions_state_scheduled",
        "execution_sessions",
        ["session_state", "scheduled_start_at"],
        unique=False,
    )
    op.create_index(
        "ix_execution_sessions_task_created",
        "execution_sessions",
        ["task_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "feature_snapshots",
        sa.Column("feature_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("window_60_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_300_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_60_coverage_seconds", sa.Float(), nullable=False),
        sa.Column("window_300_coverage_seconds", sa.Float(), nullable=False),
        sa.Column("allowed_app_ratio_60s", sa.Float(), nullable=False),
        sa.Column("blocked_app_ratio_60s", sa.Float(), nullable=False),
        sa.Column("blocked_continuous_seconds", sa.Float(), nullable=False),
        sa.Column("allowed_continuous_seconds", sa.Float(), nullable=False),
        sa.Column("idle_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "sensor_conflict", sa.Boolean(), server_default=sa.text("(false)"), nullable=False
        ),
        sa.Column(
            "source_observation_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "allowed_app_ratio_60s BETWEEN 0 AND 1",
            name=op.f("ck_feature_snapshots_allowed_ratio_range"),
        ),
        sa.CheckConstraint(
            "allowed_continuous_seconds >= 0",
            name=op.f("ck_feature_snapshots_allowed_continuous_nonnegative"),
        ),
        sa.CheckConstraint(
            "blocked_app_ratio_60s BETWEEN 0 AND 1",
            name=op.f("ck_feature_snapshots_blocked_ratio_range"),
        ),
        sa.CheckConstraint(
            "blocked_continuous_seconds >= 0",
            name=op.f("ck_feature_snapshots_blocked_continuous_nonnegative"),
        ),
        sa.CheckConstraint(
            "idle_seconds IS NULL OR idle_seconds >= 0",
            name=op.f("ck_feature_snapshots_idle_nonnegative"),
        ),
        sa.CheckConstraint(
            "window_300_coverage_seconds BETWEEN 0 AND 300",
            name=op.f("ck_feature_snapshots_window_300_coverage_range"),
        ),
        sa.CheckConstraint(
            "window_60_coverage_seconds BETWEEN 0 AND 60",
            name=op.f("ck_feature_snapshots_window_60_coverage_range"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
            name=op.f("fk_feature_snapshots_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["execution_sessions.session_id"],
            name=op.f("fk_feature_snapshots_session_id_execution_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("feature_snapshot_id", name=op.f("pk_feature_snapshots")),
    )
    op.create_index(
        "ix_feature_snapshots_device_computed",
        "feature_snapshots",
        ["device_id", "computed_at"],
        unique=False,
    )
    op.create_index(
        "ix_feature_snapshots_session_computed",
        "feature_snapshots",
        ["session_id", "computed_at"],
        unique=False,
    )
    op.create_table(
        "observations",
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.String(length=16), server_default="1.0", nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('ACTIVITY_SAMPLE','LOCK_STATE','SESSION_STATE',"
            "'MANUAL_CHECK_IN','SENSOR_STATUS')",
            name=op.f("ck_observations_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
            name=op.f("fk_observations_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["execution_sessions.session_id"],
            name=op.f("fk_observations_session_id_execution_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("observation_id", name=op.f("pk_observations")),
        sa.UniqueConstraint("idempotency_key", name="uq_observations_idempotency_key"),
    )
    op.create_index(
        "ix_observations_device_observed",
        "observations",
        ["device_id", "observed_at"],
        unique=False,
    )
    op.create_index("ix_observations_received", "observations", ["received_at"], unique=False)
    op.create_index(
        "ix_observations_session_observed",
        "observations",
        ["session_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "runtime_states",
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("feature_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("estimated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("context", sa.String(length=24), nullable=False),
        sa.Column("presence", sa.String(length=16), nullable=False),
        sa.Column("engagement", sa.String(length=16), nullable=False),
        sa.Column("session_state", sa.String(length=24), nullable=False),
        sa.Column("device_role", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "context IN ('FOCUS','CLASS','BREAK','MEAL','TRAVEL','FREE',"
            "'SLEEP','RECOVERY','EMERGENCY','UNPLANNED')",
            name=op.f("ck_runtime_states_context"),
        ),
        sa.CheckConstraint(
            "device_role IN ('PRIMARY_INTERACTION','PRIMARY_ENFORCEMENT','SENSOR',"
            "'NOTIFICATION_ONLY','AI_WORKER','STANDBY')",
            name=op.f("ck_runtime_states_device_role"),
        ),
        sa.CheckConstraint(
            "engagement IN ('ON_TASK','OFF_TASK','IDLE','UNKNOWN')",
            name=op.f("ck_runtime_states_engagement"),
        ),
        sa.CheckConstraint(
            "presence IN ('PRESENT','ABSENT','UNKNOWN')", name=op.f("ck_runtime_states_presence")
        ),
        sa.CheckConstraint(
            "session_state IN ('PLANNED','DUE','STARTING','RUNNING','PAUSED',"
            "'INTERRUPTED','RECOVERY','COMPLETED','ABORTED','MISSED')",
            name=op.f("ck_runtime_states_session_state"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_runtime_states_confidence_range")
        ),
        sa.CheckConstraint(
            "state_version >= 1", name=op.f("ck_runtime_states_state_version_positive")
        ),
        sa.CheckConstraint(
            "valid_until > estimated_at", name=op.f("ck_runtime_states_valid_interval")
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
            name=op.f("fk_runtime_states_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["feature_snapshot_id"],
            ["feature_snapshots.feature_snapshot_id"],
            name=op.f("fk_runtime_states_feature_snapshot_id_feature_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["execution_sessions.session_id"],
            name=op.f("fk_runtime_states_session_id_execution_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("state_id", name=op.f("pk_runtime_states")),
        sa.UniqueConstraint(
            "device_id", "state_version", name="uq_runtime_states_device_state_version"
        ),
    )
    op.create_index(
        "ix_runtime_states_device_estimated",
        "runtime_states",
        ["device_id", "estimated_at"],
        unique=False,
    )
    op.create_index(
        "ix_runtime_states_session_estimated",
        "runtime_states",
        ["session_id", "estimated_at"],
        unique=False,
    )
    op.create_table(
        "policy_decisions",
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("commitment_mode", sa.String(length=16), nullable=False),
        sa.Column("intervention_level", sa.SmallInteger(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("dry_run", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "commitment_mode IN ('ADVISORY','STANDARD','STRICT')",
            name=op.f("ck_policy_decisions_commitment_mode"),
        ),
        sa.CheckConstraint(
            "risk_level IN ('SAFE','HARD')", name=op.f("ck_policy_decisions_risk_level")
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > decided_at",
            name=op.f("ck_policy_decisions_valid_expiry"),
        ),
        sa.CheckConstraint(
            "intervention_level BETWEEN 0 AND 5",
            name=op.f("ck_policy_decisions_intervention_level_range"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["execution_sessions.session_id"],
            name=op.f("fk_policy_decisions_session_id_execution_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["runtime_states.state_id"],
            name=op.f("fk_policy_decisions_state_id_runtime_states"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_policy_decisions")),
        sa.UniqueConstraint("idempotency_key", name="uq_policy_decisions_idempotency_key"),
    )
    op.create_index(
        "ix_policy_decisions_session_decided",
        "policy_decisions",
        ["session_id", "decided_at"],
        unique=False,
    )
    op.create_index(
        "ix_policy_decisions_state_version", "policy_decisions", ["state_version"], unique=False
    )
    op.create_table(
        "runtime_state_heads",
        sa.Column("runtime_state_head_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("current_state_id", sa.Uuid(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "state_version >= 1", name=op.f("ck_runtime_state_heads_state_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["current_state_id"],
            ["runtime_states.state_id"],
            name=op.f("fk_runtime_state_heads_current_state_id_runtime_states"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
            name=op.f("fk_runtime_state_heads_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("runtime_state_head_id", name=op.f("pk_runtime_state_heads")),
        sa.UniqueConstraint("device_id", name="uq_runtime_state_heads_device_id"),
    )
    op.create_table(
        "commands",
        sa.Column("command_id", sa.Uuid(), nullable=False),
        sa.Column("target_device_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("role_lease_id", sa.Uuid(), nullable=True),
        sa.Column("authorized_commitment_mode", sa.String(length=16), nullable=False),
        sa.Column("command_type", sa.String(length=32), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("required_state_version", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "authorized_commitment_mode IN ('ADVISORY','STANDARD','STRICT')",
            name=op.f("ck_commands_commitment_mode"),
        ),
        sa.CheckConstraint(
            "command_type IN ('SHOW_NOTIFICATION','SHOW_CONFIRMATION','WOULD_BLOCK',"
            "'START_BLOCK','ENTER_RECOVERY','RELEASE_ALL')",
            name=op.f("ck_commands_command_type"),
        ),
        sa.CheckConstraint(
            "risk_level != 'HARD' OR authorized_commitment_mode IN ('STANDARD','STRICT')",
            name=op.f("ck_commands_hard_requires_authority"),
        ),
        sa.CheckConstraint(
            "risk_level != 'HARD' OR role_lease_id IS NOT NULL",
            name=op.f("ck_commands_hard_requires_lease"),
        ),
        sa.CheckConstraint("risk_level IN ('SAFE','HARD')", name=op.f("ck_commands_risk_level")),
        sa.CheckConstraint(
            "status IN ('PENDING','DELIVERED','ACKED','REJECTED','EXPIRED','CANCELLED')",
            name=op.f("ck_commands_status"),
        ),
        sa.CheckConstraint(
            "expires_at > not_before AND not_before >= issued_at",
            name=op.f("ck_commands_valid_window"),
        ),
        sa.CheckConstraint(
            "required_state_version >= 1", name=op.f("ck_commands_state_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["policy_decisions.decision_id"],
            name=op.f("fk_commands_decision_id_policy_decisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_lease_id"],
            ["device_role_leases.lease_id"],
            name=op.f("fk_commands_role_lease_id_device_role_leases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["execution_sessions.session_id"],
            name=op.f("fk_commands_session_id_execution_sessions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_device_id"],
            ["devices.device_id"],
            name=op.f("fk_commands_target_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("command_id", name=op.f("pk_commands")),
        sa.UniqueConstraint("idempotency_key", name="uq_commands_idempotency_key"),
    )
    op.create_index("ix_commands_decision", "commands", ["decision_id"], unique=False)
    op.create_index(
        "ix_commands_session_issued", "commands", ["session_id", "issued_at"], unique=False
    )
    op.create_index(
        "ix_commands_target_status_window",
        "commands",
        ["target_device_id", "status", "not_before", "expires_at"],
        unique=False,
    )
    op.create_table(
        "command_acks",
        sa.Column("ack_id", sa.Uuid(), nullable=False),
        sa.Column("command_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("observed_state_version", sa.Integer(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "status IN ('ACCEPTED','EXECUTED','REJECTED','EXPIRED','STALE','FAILED')",
            name=op.f("ck_command_acks_status"),
        ),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["commands.command_id"],
            name=op.f("fk_command_acks_command_id_commands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
            name=op.f("fk_command_acks_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("ack_id", name=op.f("pk_command_acks")),
        sa.UniqueConstraint("idempotency_key", name="uq_command_acks_idempotency_key"),
    )
    op.create_index(
        "ix_command_acks_command_acknowledged",
        "command_acks",
        ["command_id", "acknowledged_at"],
        unique=False,
    )
    op.create_index(
        "ix_command_acks_device_acknowledged",
        "command_acks",
        ["device_id", "acknowledged_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_command_acks_device_acknowledged", table_name="command_acks")
    op.drop_index("ix_command_acks_command_acknowledged", table_name="command_acks")
    op.drop_table("command_acks")
    op.drop_index("ix_commands_target_status_window", table_name="commands")
    op.drop_index("ix_commands_session_issued", table_name="commands")
    op.drop_index("ix_commands_decision", table_name="commands")
    op.drop_table("commands")
    op.drop_table("runtime_state_heads")
    op.drop_index("ix_policy_decisions_state_version", table_name="policy_decisions")
    op.drop_index("ix_policy_decisions_session_decided", table_name="policy_decisions")
    op.drop_table("policy_decisions")
    op.drop_index("ix_runtime_states_session_estimated", table_name="runtime_states")
    op.drop_index("ix_runtime_states_device_estimated", table_name="runtime_states")
    op.drop_table("runtime_states")
    op.drop_index("ix_observations_session_observed", table_name="observations")
    op.drop_index("ix_observations_received", table_name="observations")
    op.drop_index("ix_observations_device_observed", table_name="observations")
    op.drop_table("observations")
    op.drop_index("ix_feature_snapshots_session_computed", table_name="feature_snapshots")
    op.drop_index("ix_feature_snapshots_device_computed", table_name="feature_snapshots")
    op.drop_table("feature_snapshots")
    op.drop_index("ix_execution_sessions_task_created", table_name="execution_sessions")
    op.drop_index("ix_execution_sessions_state_scheduled", table_name="execution_sessions")
    op.drop_table("execution_sessions")
    op.drop_index("ix_schedule_blocks_task_start", table_name="schedule_blocks")
    op.drop_index("ix_schedule_blocks_plan_start", table_name="schedule_blocks")
    op.drop_table("schedule_blocks")
    op.drop_table("plan_heads")
    op.drop_index("ix_outbox_status_available", table_name="outbox")
    op.drop_index("ix_outbox_locked", table_name="outbox")
    op.drop_table("outbox")
    op.drop_index("ix_device_role_leases_role_expiry", table_name="device_role_leases")
    op.drop_index("ix_device_role_leases_device_expiry", table_name="device_role_leases")
    op.drop_table("device_role_leases")
    op.drop_index("ix_daily_summaries_date", table_name="daily_summaries")
    op.drop_table("daily_summaries")
    op.drop_index("ix_tasks_status_deadline", table_name="tasks")
    op.drop_index("ix_tasks_mandatory_priority", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_plan_versions_date_created", table_name="plan_versions")
    op.drop_table("plan_versions")
    op.drop_index("ix_fixed_events_start_end", table_name="fixed_events")
    op.drop_table("fixed_events")
    op.drop_index("ix_event_ledger_type_occurred", table_name="event_ledger")
    op.drop_index("ix_event_ledger_entity_received", table_name="event_ledger")
    op.drop_index("ix_event_ledger_correlation", table_name="event_ledger")
    op.drop_table("event_ledger")
    op.drop_index("ix_devices_status_heartbeat", table_name="devices")
    op.drop_table("devices")
    op.drop_index("ix_ai_jobs_status_available", table_name="ai_jobs")
    op.drop_index("ix_ai_jobs_provider_created", table_name="ai_jobs")
    op.drop_table("ai_jobs")
    # ### end Alembic commands ###
